use_frameworks!

platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jsonsnow/CLSpces.git'

target 'DynamicRoute_Example' do
  pod 'DynamicRoute', :path => '../'

  target 'DynamicRoute_Tests' do
    inherit! :search_paths

    
  end
end
